### ISSUE TITLE
Issues when left alone for long periods 

### ISSUE THREAD

**Issue by JackyChiu** [Hacker-Chatroom/Hacker-Chatroom-Client#19]
The chat seems so connect to the room multiple times when left alone. This results in the user's message being amplified multiple times. This also results in a memory leak according to the warnings. Still need more details of the behavior. 

Possible reasons: 
- Heroku server sleeps after 30mins of inactivity 
- Web socket behavior with socket.io

**Comment by JackyChiu** [comment]
Here's a image of the case
<img width="334" alt="screen shot 2017-01-07 at 1 59 01 pm" src="https://cloud.githubusercontent.com/assets/11095732/21744347/9a879252-d4e1-11e6-8d93-a250c78cf6f0.png">

**Comment by BenEmdon** [comment]
Hi I am a user of HackerChat. Ths is still a big issue!! pls fix!!1 Thanks

**Comment by JackyChiu** [comment]
@BenEmdon please donate to our patreon to meet our goal of $2000 a month to continue development!

**Comment by BenEmdon** [comment]
I am do nt haeve much money, I am only a hacker
