### ISSUE TITLE
Odd % sign beside timestamp

### ISSUE THREAD

**Issue by JackyChiu** [Hacker-Chatroom/Hacker-Chatroom-Client#2]
<img width="169" alt="screen shot 2016-10-30 at 5 46 21 pm" src="https://cloud.githubusercontent.com/assets/11095732/19840289/d5a0d7e4-9ec8-11e6-9961-f5ef4aacb3ec.png">

**Comment by JackyChiu** [comment]
@Tuanhao Do you want to try to fix this?

**Comment by kirinrastogi** [comment]
Maybe try reversing the order of the color for yellow to {0, 30, 43}, I tried this locally and it works, but it affects all text after the username as well. Do we also need to add a Color that resets the input to black background and white foreground?

**Comment by JackyChiu** [comment]
Oh nice fix. Yeah we might need to do the reset of the colours than

**Comment by JackyChiu** [comment]
@Tuanhao What is the `%s` for in `\x1b[0m\x1b[30m\x1b[43m`?

**Comment by Tuanhao** [comment]
The "%s" is like a sign so that the machine know the following text will apply the color code that is after "%s". In the color module, everything after "%s" is the code to clear all color.
